repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      # # line length compatible with black and flake8
      - id: docformatter
        args: [--wrap-summaries, "79", --in-place]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
    - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent giant files from being committed.
      - id: check-added-large-files
        args: ['--maxkb=500']

        # Simply check whether files parse as valid python.
      - id: check-ast

      # Attempts to load all json files to verify syntax.
      - id: check-json

      # Checks for symlinks which do not point to anything.
      - id: check-symlinks

      # Attempts to load all xml files to verify syntax.
      - id: check-xml

      # Attempts to load all yaml files to verify syntax.
      - id: check-yaml

      # Check for files that contain merge conflict strings.
      - id: check-merge-conflict

      # Attempts to load all TOML files to verify syntax.
      - id: check-toml

      # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: debug-statements

      # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      - id: destroyed-symlinks

      # Makes sure files end in a newline and only a newline.
      - id: end-of-file-fixer

      # Assert that files in tests/ start in test_*.py.
      - id: name-tests-test
        args: ['--django']

      # Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
      - id: requirements-txt-fixer

      # Trims trailing whitespace.
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
